# Apresentação:

O propósito desse notebook é construir uma estrutura de verificação da integridade dos objetos do minio.

In [1]:
# Dependencias de ambiente
import os 
from dotenv import load_dotenv
from organizer import path_organizer

In [2]:
# Carregando variáveis de ambiente
load_dotenv()

True

In [3]:
# Adicionando diretório ao sistema
path_organizer()

Raiz do projeto adicionada: e:\iplanrio-desafio-data-eng

In [4]:
# Dependências
import duckdb
import polars as pl
from pipeline.OStorage import MinioClient
from pathlib import PurePosixPath

# Verificando Arquivos

In [5]:
minio = MinioClient()

In [6]:
buckets = minio.list_buckets();buckets

['terceirizados']

In [7]:
files = minio.list_objects(buckets[0]);files

['bronze/terceirizados-bronze.duckdb',
 'raw/terceirizados_2019_janeiro.parquet',
 'raw/terceirizados_2019_maio.parquet',
 'raw/terceirizados_2019_setembro.parquet',
 'raw/terceirizados_2020_janeiro.parquet',
 'raw/terceirizados_2020_maio.parquet',
 'raw/terceirizados_2020_setembro.parquet',
 'raw/terceirizados_2021_janeiro.parquet',
 'raw/terceirizados_2021_maio.parquet',
 'raw/terceirizados_2021_setembro.parquet',
 'raw/terceirizados_2022_janeiro.parquet',
 'raw/terceirizados_2022_maio.parquet',
 'raw/terceirizados_2022_setembro.parquet',
 'raw/terceirizados_2023_janeiro.parquet',
 'raw/terceirizados_2023_maio.parquet',
 'raw/terceirizados_2023_setembro.parquet',
 'raw/terceirizados_2024_janeiro.parquet',
 'raw/terceirizados_2024_maio.parquet',
 'raw/terceirizados_2024_setembro.parquet',
 'raw/terceirizados_2025_janeiro.parquet',
 'raw/terceirizados_2025_maio.parquet',
 'raw/terceirizados_2025_setembro.parquet']

In [8]:
objects = {
    PurePosixPath(file).stem:minio.get_object(
        bucket_name=buckets[0],
        object_name=file
        ) 
        for file in minio.list_objects(buckets[0])[1:]
    }

In [9]:
objects

{'terceirizados_2019_janeiro': <_io.BytesIO at 0x29d083929d0>,
 'terceirizados_2019_maio': <_io.BytesIO at 0x29d08390090>,
 'terceirizados_2019_setembro': <_io.BytesIO at 0x29d08391f30>,
 'terceirizados_2020_janeiro': <_io.BytesIO at 0x29d0837d170>,
 'terceirizados_2020_maio': <_io.BytesIO at 0x29d083909a0>,
 'terceirizados_2020_setembro': <_io.BytesIO at 0x29d08390400>,
 'terceirizados_2021_janeiro': <_io.BytesIO at 0x29d08390770>,
 'terceirizados_2021_maio': <_io.BytesIO at 0x29d08391b70>,
 'terceirizados_2021_setembro': <_io.BytesIO at 0x29d08390fe0>,
 'terceirizados_2022_janeiro': <_io.BytesIO at 0x29d083906d0>,
 'terceirizados_2022_maio': <_io.BytesIO at 0x29d08390680>,
 'terceirizados_2022_setembro': <_io.BytesIO at 0x29d08390e50>,
 'terceirizados_2023_janeiro': <_io.BytesIO at 0x29d08390810>,
 'terceirizados_2023_maio': <_io.BytesIO at 0x29d08391170>,
 'terceirizados_2023_setembro': <_io.BytesIO at 0x29d08391030>,
 'terceirizados_2024_janeiro': <_io.BytesIO at 0x29d08393d30>,
 'terceirizados_2024_maio': <_io.BytesIO at 0x29d08390950>,
 'terceirizados_2024_setembro': <_io.BytesIO at 0x29d08391260>,
 'terceirizados_2025_janeiro': <_io.BytesIO at 0x29d08390f90>,
 'terceirizados_2025_maio': <_io.BytesIO at 0x29d08390cc0>,
 'terceirizados_2025_setembro': <_io.BytesIO at 0x29d08391e90>}

In [10]:
# Lendo um parquet:
df = pl.read_parquet(objects["terceirizados_2022_setembro"]);df.head()

shape: (5, 25)
┌─────────┬─────────────┬─────────────┬────────────┬───┬────────────┬────────────┬──────┬──────────┐
│ id_terc ┆ sg_orgao_su ┆ cd_ug_gesto ┆ nm_ug_tabe ┆ … ┆ cd_orgao_s ┆ cd_orgao_s ┆ ano  ┆ mes      │
│ ---     ┆ p_tabela_ug ┆ ra          ┆ la_ug      ┆   ┆ iafi       ┆ iape       ┆ ---  ┆ ---      │
│ i64     ┆ ---         ┆ ---         ┆ ---        ┆   ┆ ---        ┆ ---        ┆ i32  ┆ str      │
│         ┆ str         ┆ i64         ┆ str        ┆   ┆ i64        ┆ i64        ┆      ┆          │
╞═════════╪═════════════╪═════════════╪════════════╪═══╪════════════╪════════════╪══════╪══════════╡
│ 8363540 ┆ M.CIDADA    ┆ 550005      ┆ COORDENACA ┆ … ┆ 55000      ┆ 55000      ┆ 2022 ┆ Setembro │
│         ┆             ┆             ┆ O GERAL DE ┆   ┆            ┆            ┆      ┆          │
│         ┆             ┆             ┆ LICITACOE… ┆   ┆            ┆            ┆      ┆          │
│ 8363541 ┆ M.CIDADA    ┆ 550005      ┆ COORDENACA ┆ … ┆ 55000      ┆ 55000      ┆ 2022 ┆ Setembro │
│         ┆             ┆             ┆ O GERAL DE ┆   ┆            ┆            ┆      ┆          │
│         ┆             ┆             ┆ LICITACOE… ┆   ┆            ┆            ┆      ┆          │
│ 8363542 ┆ M.CIDADA    ┆ 550005      ┆ COORDENACA ┆ … ┆ 55000      ┆ 55000      ┆ 2022 ┆ Setembro │
│         ┆             ┆             ┆ O GERAL DE ┆   ┆            ┆            ┆      ┆          │
│         ┆             ┆             ┆ LICITACOE… ┆   ┆            ┆            ┆      ┆          │
│ 8363543 ┆ M.CIDADA    ┆ 550005      ┆ COORDENACA ┆ … ┆ 55000      ┆ 55000      ┆ 2022 ┆ Setembro │
│         ┆             ┆             ┆ O GERAL DE ┆   ┆            ┆            ┆      ┆          │
│         ┆             ┆             ┆ LICITACOE… ┆   ┆            ┆            ┆      ┆          │
│ 8363544 ┆ M.CIDADA    ┆ 550005      ┆ COORDENACA ┆ … ┆ 55000      ┆ 55000      ┆ 2022 ┆ Setembro │
│         ┆             ┆             ┆ O GERAL DE ┆   ┆            ┆            ┆      ┆          │
│         ┆             ┆             ┆ LICITACOE… ┆   ┆            ┆            ┆      ┆          │
└─────────┴─────────────┴─────────────┴────────────┴───┴────────────┴────────────┴──────┴──────────┘

In [10]:
# lendo os parquets:
parquet_dfs = []

for name, buffer in objects.items():
    if name.endswith("bronze"):
        continue

    buffer.seek(0)
    parquet_dfs.append(pl.read_parquet(buffer))

In [12]:
parquet_dfs[0]

shape: (97_828, 25)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬──────┬─────────┐
│ id_terc    ┆ sg_orgao_s ┆ cd_ug_gest ┆ nm_ug_tabe ┆ … ┆ cd_orgao_s ┆ cd_orgao_s ┆ ano  ┆ mes     │
│ ---        ┆ up_tabela_ ┆ ora        ┆ la_ug      ┆   ┆ iafi       ┆ iape       ┆ ---  ┆ ---     │
│ str        ┆ ug         ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ i32  ┆ str     │
│            ┆ ---        ┆ str        ┆ str        ┆   ┆ str        ┆ str        ┆      ┆         │
│            ┆ str        ┆            ┆            ┆   ┆            ┆            ┆      ┆         │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪══════╪═════════╡
│ ï»¿7070352 ┆ M.J        ┆ 200109     ┆ DEPARTAMEN ┆ … ┆ 30802      ┆ 30802      ┆ 2019 ┆ Janeiro │
│            ┆            ┆            ┆ TO DE      ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ POLICIA    ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ RODOVI…    ┆   ┆            ┆            ┆      ┆         │
│ 7070353    ┆ M.J        ┆ 200109     ┆ DEPARTAMEN ┆ … ┆ 30802      ┆ 30802      ┆ 2019 ┆ Janeiro │
│            ┆            ┆            ┆ TO DE      ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ POLICIA    ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ RODOVI…    ┆   ┆            ┆            ┆      ┆         │
│ 7070354    ┆ M.J        ┆ 200109     ┆ DEPARTAMEN ┆ … ┆ 30802      ┆ 30802      ┆ 2019 ┆ Janeiro │
│            ┆            ┆            ┆ TO DE      ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ POLICIA    ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ RODOVI…    ┆   ┆            ┆            ┆      ┆         │
│ 7070355    ┆ M.J        ┆ 200109     ┆ DEPARTAMEN ┆ … ┆ 30802      ┆ 30802      ┆ 2019 ┆ Janeiro │
│            ┆            ┆            ┆ TO DE      ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ POLICIA    ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ RODOVI…    ┆   ┆            ┆            ┆      ┆         │
│ 7070356    ┆ M.J        ┆ 200109     ┆ DEPARTAMEN ┆ … ┆ 30802      ┆ 30802      ┆ 2019 ┆ Janeiro │
│            ┆            ┆            ┆ TO DE      ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ POLICIA    ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ RODOVI…    ┆   ┆            ┆            ┆      ┆         │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …    ┆ …       │
│ 7168078    ┆ PR         ┆ 373085     ┆ SUPERINTEN ┆ … ┆ 22201      ┆ 42201      ┆ 2019 ┆ Janeiro │
│            ┆            ┆            ┆ DENCIA     ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ REGIONAL   ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ DE T…      ┆   ┆            ┆            ┆      ┆         │
│ 7168079    ┆ PR         ┆ 373085     ┆ SUPERINTEN ┆ … ┆ 22201      ┆ 42201      ┆ 2019 ┆ Janeiro │
│            ┆            ┆            ┆ DENCIA     ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ REGIONAL   ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ DE T…      ┆   ┆            ┆            ┆      ┆         │
│ 7168080    ┆ PR         ┆ 373085     ┆ SUPERINTEN ┆ … ┆ 22201      ┆ 42201      ┆ 2019 ┆ Janeiro │
│            ┆            ┆            ┆ DENCIA     ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ REGIONAL   ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ DE T…      ┆   ┆            ┆            ┆      ┆         │
│ 7168081    ┆ PR         ┆ 373085     ┆ SUPERINTEN ┆ … ┆ 22201      ┆ 42201      ┆ 2019 ┆ Janeiro │
│            ┆            ┆            ┆ DENCIA     ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ REGIONAL   ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ DE T…      ┆   ┆            ┆            ┆      ┆         │
│ 7168082    ┆ PR         ┆ 373085     ┆ SUPERINTEN ┆ … ┆ 22201      ┆ 42201      ┆ 2019 ┆ Janeiro │
│            ┆            ┆            ┆ DENCIA     ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ REGIONAL   ┆   ┆            ┆            ┆      ┆         │
│            ┆            ┆            ┆ DE T…      ┆   ┆            ┆            ┆      ┆         │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴──────┴─────────┘

In [12]:
import duckdb
import tempfile
import polars as pl

In [ ]:
duck_dfs = []

duck_buffer = minio.get_object(
    bucket_name=buckets[0],
    object_name=files[0]
)

duck_buffer.seek(0)

# cria arquivo temporário SEM manter aberto
tmp = tempfile.NamedTemporaryFile(suffix=".duckdb", delete=False)
tmp.write(duck_buffer.read())
tmp.close()   # 🔥 ESSENCIAL NO WINDOWS

# agora pode abrir com duckdb
con = duckdb.connect(tmp.name)

table_names = [
    row[0]
    for row in con.execute("SHOW TABLES").fetchall()
]

for table in table_names:
    df = con.execute(f"SELECT * FROM {table}").pl()
    duck_dfs.append(df)

con.close()

In [25]:
parquet_dfs[1].columns

['id_terc',
 'sg_orgao_sup_tabela_ug',
 'cd_ug_gestora',
 'nm_ug_tabela_ug',
 'sg_ug_gestora',
 'nr_contrato',
 'nr_cnpj',
 'nm_razao_social',
 'nr_cpf',
 'nm_terceirizado',
 'nm_categoria_profissional',
 'nm_escolaridade',
 'nr_jornada',
 'nm_unidade_prestacao',
 'vl_mensal_salario',
 'vl_mensal_custo',
 'Num_Mes_Carga',
 'Mes_Carga',
 'Ano_Carga',
 'sg_orgao',
 'nm_orgao',
 'cd_orgao_siafi',
 'cd_orgao_siape',
 'ano',
 'mes']

In [16]:
results = []

for p_df, d_df in zip(parquet_dfs, duck_dfs):
    equal = (
        p_df.join(d_df, on="id", how="anti").height == 0
        and
        d_df.join(p_df, on="id", how="anti").height == 0
    )
    results.append(equal)

print(results)

ColumnNotFoundError: unable to find column "id"; valid columns: ["ï»¿7070352", "M.J", "200109", "DEPARTAMENTO DE POLICIA RODOVIARIA FEDERAL", "DPRF", "06/2018", "06311155000125", "CS SEGURACA E VIGILANCIA LTDA", "***.896.391-**", "FRANCISCO DOS SANTOS FRANCA", "517330 - VIGILANTE", "ENSINO FUNDAMENTAL INCOMPLETO", "48  ", "PRF", "2012,55", "13101,44", "1", "JANEIRO", "2019", "DPRF/MJ", "DEPARTAMENTO DE POLICIA RODOVIARIA FEDERAL/MJ", "30802", "30802_duplicated_0", "ano", "mes"]